[package]

name = "iron"
version = "0.0.2"
description = "Middleware-Oriented, Concurrency Focused Web Development in Rust."
readme = "README.md"
documentation = "http://ironframework.io/doc/iron/"
license = "MIT"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Patrick Tran <patrick.tran06@gmail.com>",
    "Michael Reinhard <mcreinhard@gmail.com>"]

[lib]

name = "iron"
path = "src/lib.rs"

[dependencies]
hyper = "*"
typemap = "*"
url = "*"
plugin = "*"
modifier = "*"
error = "*"

