[package]

name = "iron"
version = "0.0.1"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Patrick Tran <patrick.tran06@gmail.com>",
    "Michael Reinhard <mcreinhard@gmail.com>"]

[lib]

name = "iron"
path = "src/lib.rs"

[dependencies]
hyper = "*"
typemap = "*"
url = "*"
plugin = "*"
modifier = "*"
error = "*"

