[package]

name = "iron"
version = "0.0.0"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Patrick Tran <patrick.tran06@gmail.com>",
    "Michael Reinhard <mcreinhard@gmail.com>"]

[[lib]]

name = "iron"
path = "src/lib.rs"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.anymap]

git = "https://github.com/chris-morgan/anymap.git"

[dependencies.content-type]

git = "https://github.com/reem/rust-http-content-type.git"

[dependencies.url]

git = "https://github.com/servo/rust-url.git"
