[package]

name = "iron"
version = "0.1.12"
description = "Extensible, Concurrency Focused Web Development in Rust."
readme = "README.md"
repository = "https://github.com/iron/iron"
documentation = "http://ironframework.io/doc/iron/"
license = "MIT"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Michael Sproul <micsproul@gmail.com>",
    "Patrick Tran <patrick.tran06@gmail.com>"
]

[lib]

name = "iron"
path = "src/lib.rs"

[dependencies]
hyper = "*"
typemap = "*"
url = "*"
plugin = "*"
modifier = "*"
error = "*"
log = "*"
conduit-mime-types = "*"
lazy_static = "*"
num_cpus = "*"

[dev-dependencies]
time = "*"

